# fly.toml app configuration file generated for blazehorse-demo on 2023-06-09T11:18:53-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "blazehorse-demo"
primary_region = "yyz"
console_command = "/code/manage.py shell"

[env]
  PORT = "8000"

[[mounts]]
  source = "storage"
  destination = "/mnt/storage"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"
